package gt.research.losf.journal.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import gt.research.losf.journal.db.Block;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BLOCK".
*/
public class BlockDao extends AbstractDao<Block, Integer> {

    public static final String TABLENAME = "BLOCK";

    /**
     * Properties of entity Block.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, int.class, "id", true, "ID");
        public final static Property Url = new Property(1, String.class, "url", false, "URL");
        public final static Property FileOffset = new Property(2, int.class, "fileOffset", false, "FILE_OFFSET");
        public final static Property DownloadOffset = new Property(3, int.class, "downloadOffset", false, "DOWNLOAD_OFFSET");
        public final static Property Read = new Property(4, int.class, "read", false, "READ");
        public final static Property Length = new Property(5, int.class, "length", false, "LENGTH");
        public final static Property File = new Property(6, String.class, "file", false, "FILE");
        public final static Property Network = new Property(7, int.class, "network", false, "NETWORK");
        public final static Property Retry = new Property(8, int.class, "retry", false, "RETRY");
        public final static Property Md5 = new Property(9, String.class, "md5", false, "MD5");
    };


    public BlockDao(DaoConfig config) {
        super(config);
    }
    
    public BlockDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BLOCK\" (" + //
                "\"ID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"URL\" TEXT NOT NULL ," + // 1: url
                "\"FILE_OFFSET\" INTEGER NOT NULL ," + // 2: fileOffset
                "\"DOWNLOAD_OFFSET\" INTEGER NOT NULL ," + // 3: downloadOffset
                "\"READ\" INTEGER NOT NULL ," + // 4: read
                "\"LENGTH\" INTEGER NOT NULL ," + // 5: length
                "\"FILE\" TEXT NOT NULL ," + // 6: file
                "\"NETWORK\" INTEGER NOT NULL ," + // 7: network
                "\"RETRY\" INTEGER NOT NULL ," + // 8: retry
                "\"MD5\" TEXT NOT NULL );"); // 9: md5
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_BLOCK_ID ON BLOCK" +
                " (\"ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BLOCK\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Block entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getUrl());
        stmt.bindLong(3, entity.getFileOffset());
        stmt.bindLong(4, entity.getDownloadOffset());
        stmt.bindLong(5, entity.getRead());
        stmt.bindLong(6, entity.getLength());
        stmt.bindString(7, entity.getFile());
        stmt.bindLong(8, entity.getNetwork());
        stmt.bindLong(9, entity.getRetry());
        stmt.bindString(10, entity.getMd5());
    }

    /** @inheritdoc */
    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.getInt(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Block readEntity(Cursor cursor, int offset) {
        Block entity = new Block( //
            cursor.getInt(offset + 0), // id
            cursor.getString(offset + 1), // url
            cursor.getInt(offset + 2), // fileOffset
            cursor.getInt(offset + 3), // downloadOffset
            cursor.getInt(offset + 4), // read
            cursor.getInt(offset + 5), // length
            cursor.getString(offset + 6), // file
            cursor.getInt(offset + 7), // network
            cursor.getInt(offset + 8), // retry
            cursor.getString(offset + 9) // md5
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Block entity, int offset) {
        entity.setId(cursor.getInt(offset + 0));
        entity.setUrl(cursor.getString(offset + 1));
        entity.setFileOffset(cursor.getInt(offset + 2));
        entity.setDownloadOffset(cursor.getInt(offset + 3));
        entity.setRead(cursor.getInt(offset + 4));
        entity.setLength(cursor.getInt(offset + 5));
        entity.setFile(cursor.getString(offset + 6));
        entity.setNetwork(cursor.getInt(offset + 7));
        entity.setRetry(cursor.getInt(offset + 8));
        entity.setMd5(cursor.getString(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Integer updateKeyAfterInsert(Block entity, long rowId) {
        return entity.getId();
    }
    
    /** @inheritdoc */
    @Override
    public Integer getKey(Block entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
