package gt.research.losf.journal.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BLOCK".
 */
public class Block {

    private int id;
    /** Not-null value. */
    private String url;
    private int fileOffset;
    private int downloadOffset;
    private int read;
    private int length;
    /** Not-null value. */
    private String file;
    private int network;
    private int retry;
    /** Not-null value. */
    private String md5;

    public Block() {
    }

    public Block(int id) {
        this.id = id;
    }

    public Block(int id, String url, int fileOffset, int downloadOffset, int read, int length, String file, int network, int retry, String md5) {
        this.id = id;
        this.url = url;
        this.fileOffset = fileOffset;
        this.downloadOffset = downloadOffset;
        this.read = read;
        this.length = length;
        this.file = file;
        this.network = network;
        this.retry = retry;
        this.md5 = md5;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public int getFileOffset() {
        return fileOffset;
    }

    public void setFileOffset(int fileOffset) {
        this.fileOffset = fileOffset;
    }

    public int getDownloadOffset() {
        return downloadOffset;
    }

    public void setDownloadOffset(int downloadOffset) {
        this.downloadOffset = downloadOffset;
    }

    public int getRead() {
        return read;
    }

    public void setRead(int read) {
        this.read = read;
    }

    public int getLength() {
        return length;
    }

    public void setLength(int length) {
        this.length = length;
    }

    /** Not-null value. */
    public String getFile() {
        return file;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFile(String file) {
        this.file = file;
    }

    public int getNetwork() {
        return network;
    }

    public void setNetwork(int network) {
        this.network = network;
    }

    public int getRetry() {
        return retry;
    }

    public void setRetry(int retry) {
        this.retry = retry;
    }

    /** Not-null value. */
    public String getMd5() {
        return md5;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMd5(String md5) {
        this.md5 = md5;
    }

}
